-- Creación de base de datos

CREATE TABLE ESTUDIANTES (
    ID_ESTUDIANTE NUMBER PRIMARY KEY, -- En Oracle, se usa NUMBER en lugar de INT
    NOMBRE VARCHAR2(100), -- En Oracle, se usa VARCHAR2 en lugar de VARCHAR
    APELLIDO VARCHAR2(100),
    EMAIL VARCHAR2(100) UNIQUE,
    FECHA_NACIMIENTO DATE
);

CREATE TABLE CURSOS (
    ID_CURSO NUMBER PRIMARY KEY, -- En Oracle, se usa NUMBER en lugar de INT
    NOMBRE_CURSO VARCHAR2(100),
    DESCRIPCION VARCHAR2(255),
    DURACION NUMBER, -- En Oracle, se usa NUMBER en lugar de INT
    PRECIO NUMBER(10,2) -- En Oracle, se usa NUMBER en lugar de DECIMAL
);

CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCION NUMBER PRIMARY KEY,
    ID_ESTUDIANTE NUMBER,
    ID_CURSO NUMBER,
    FECHA_INSCRIPCION DATE,
    CALIFICACION NUMBER,
    CONSTRAINT FK_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE) REFERENCES ESTUDIANTES(ID_ESTUDIANTE),
    CONSTRAINT FK_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSOS(ID_CURSO)
);

-- Modificar la tabla ESTUDIANTES para agregar la columna DIRECCION
ALTER TABLE ESTUDIANTES ADD DIRECCION VARCHAR2(200);

-- Modificar la columna DURACION de la tabla CURSOS (en Oracle se puede especificar la precisión)
ALTER TABLE CURSOS MODIFY DURACION NUMBER(5,1);

-- Cambiar el nombre de la columna CALIFICACION a PUNTUACION
ALTER TABLE INSCRIPCIONES RENAME COLUMN CALIFICACION TO PUNTUACION;

-- Agregar una restricción CHECK para la fecha de nacimiento en ESTUDIANTES (Verifica si la fecha de nacimiento es anterior a 192 años desde la fecha actual)
ALTER TABLE ESTUDIANTES ADD CONSTRAINT CK_FECHA_NACIMIENTO CHECK (FECHA_NACIMIENTO <= ADD_MONTHS(SYSDATE, -192 * 12));

-- Agregar una restricción UNIQUE a la columna NOMBRE_CURSO en CURSOS
ALTER TABLE CURSOS ADD CONSTRAINT UQ_NOMBRE_CURSO UNIQUE (NOMBRE_CURSO);

-- Modificar la columna PRECIO en CURSOS para asegurarse de que sea mayor o igual a 0
ALTER TABLE CURSOS ADD CONSTRAINT CK_PRECIO CHECK (PRECIO >= 0);

-- Eliminar la columna FECHA_NACIMIENTO en ESTUDIANTES
ALTER TABLE ESTUDIANTES DROP COLUMN FECHA_NACIMIENTO;

-- Deshabilitar la restricción UNIQUE en CURSOS
ALTER TABLE CURSOS DISABLE CONSTRAINT UQ_NOMBRE_CURSO;

-- Habilitar la restricción UNIQUE en CURSOS
ALTER TABLE CURSOS ENABLE CONSTRAINT UQ_NOMBRE_CURSO;